version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wallet-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: naruto123digital_wallet
      POSTGRES_DB: digital_wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: wallet-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
